### PR TITLE
update klc2ini converter

### PR DESCRIPTION
**Pull request by jlrn7**
removed deprecated encoding and utf8 dependencies.

### CODE REVIEW

**Comment by jlrn7** [comment]
I realized that encoding was deprecated when I got a warning on trying to run the script. I also found a reference on [the encoding perldoc page](http://perldoc.perl.org/encoding.html). I don't know if that is enough. Given that `encoding` is no longer necessary, I also removed the required `utf8` dependency as redundant: see the warning on the [utf8 perldoc](http://perldoc.perl.org/utf8.html) documentation. The script is ASCII clean, so the `utf8` module is unnecessary.

**Comment by presidento** [comment]
Perfect, thanks.

**Comment by jlrn7** [comment]
A caveat: on reviewing the merge I noticed that on line 145 the call

    open INI, '>:', $INIFILE;

has a typo. Perl does not detect it as a syntax error (I don't think it is) and it may not qualify as a bug. You may want to fix it directly, instead of going through a fork and merge process. My apologies.

**Comment by rubo77** [comment]
@jlrn7: what would be the fix?

**Comment by presidento** [comment]
Fixed in 103577c, thanks.

@rubo77 as I see, ">" means output file, where it was possible to set the encoding after a ":" character. I removed it.

See https://perldoc.perl.org/functions/open.html

**Pull request merged**
